---
controller_configuration_credentials_secure_logging: false
controller_credentials:
  - name: Meraki API Key
    description: Meraki Dashboard API Key
    organization: Meraki-Demo
    credential_type: Meraki Dashboard API Key
    inputs:
      auth_key: "{{ lookup('ansible.builtin.env', 'MERAKI_API_KEY', default=undef()) }}"
  - name: Github SSH Key
    description: Github SSH Key
    organization: Meraki-Demo
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ ssh_key_data }}"
      ssh_key_unlock: "{{ ssh_key_unlock }}"
  - name: Github Personal Access Token
    description: Github Token
    organization: Meraki-Demo
    credential_type: GitHub Personal Access Token
    inputs:
      token: "{{ github_token }}"
  - name: Webex Token
    description: Webex API Token
    organization: Meraki-Demo
    credential_type: Webex Token
    inputs:
      webex_token: "{{ lookup('ansible.builtin.env', 'WEBEX_TOKEN', default=undef()) }}"
